### ISSUE TITLE
Rly?!

### ISSUE THREAD

**Issue by Mike-E-angelo** [coinbase/coinbase-commerce-php#44]
Check out those fees tho:

![](https://i.imgur.com/bdBUxUP.png)

Note the `Securely signed in to Coinbase`.  However, the ginormous network fee persists, despite having enabled instant transfers on my account.

Am I expected to sell a $5 product that incurs a nearly 100% markup in network fees?  I am not sure why this interface -- although well done -- is providing the ability to sign in with Coinbase if there is no viable financial incentive to do so.

The irony is that I wanted to add Coinbase Commerce to my solution in addition to PayPal to contrast the two options, all the while denoting that "PayPal has fees" whereas Coinbase does not.  While technically true, the _network fees_ are a killer and make PayPal look like a steal at this point.

Finally, I'm digging how [Coinbase Commerce's last tweet was from last year](https://twitter.com/CommerceCB).  Is anyone still working over there?  This is the same company that recently went to market valuated at over $100B, right?

**Comment by sahil-cb** [comment]
Thanks for the feedback. Since Coinbase Commerce is a non-custodial product ATM, the merchant account is user controlled (not owned by Coinbase). Unfortunately, this is why you aren't able to leverage the instant transfer feature -- all transactions are peer-to-peer and on-chain. 

While I can't share any timelines, as we build out our custodial offering, we'll definitely be planning to leverage instant/free sends between CB accounts.
